-- 本文件在 PostgreSQL 管理员连接下创建 CMDB 全部业务结构；应用账号仅在授权范围内执行 CRUD。
\set ON_ERROR_STOP on

-- Docker 初始化约束与本保护同时确保业务表和序列由 postgres 管理员拥有。
DO $$
BEGIN
    IF current_user <> 'postgres' THEN
        RAISE EXCEPTION 'CMDB 初始化结构必须由 postgres 管理员执行';
    END IF;
END
$$;

BEGIN;

CREATE TABLE users (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username VARCHAR(64) NOT NULL CHECK (username ~ '^[A-Za-z0-9_]{1,64}$'),
    password_hash VARCHAR(255) NOT NULL,
    display_name VARCHAR(128) NOT NULL,
    email VARCHAR(255),
    global_role VARCHAR(32) NOT NULL DEFAULT 'user' CHECK (global_role IN ('system_admin', 'user')),
    status VARCHAR(32) NOT NULL DEFAULT 'active' CHECK (status IN ('active', 'disabled')),
    last_login_at TIMESTAMPTZ(3),
    created_at TIMESTAMPTZ(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    updated_at TIMESTAMPTZ(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    CONSTRAINT uk_users_username UNIQUE (username)
);

CREATE TABLE projects (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    code VARCHAR(64) NOT NULL,
    name VARCHAR(128) NOT NULL,
    description VARCHAR(500) NOT NULL DEFAULT '',
    status VARCHAR(32) NOT NULL DEFAULT 'enabled' CHECK (status IN ('enabled', 'disabled')),
    owner_user_id BIGINT,
    created_at TIMESTAMPTZ(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    updated_at TIMESTAMPTZ(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    CONSTRAINT uk_projects_code UNIQUE (code),
    CONSTRAINT fk_projects_owner_user_id FOREIGN KEY (owner_user_id) REFERENCES users (id) ON DELETE SET NULL
);

CREATE INDEX idx_projects_owner_user_id ON projects (owner_user_id);

CREATE TABLE project_members (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    project_id BIGINT NOT NULL,
    user_id BIGINT NOT NULL,
    role VARCHAR(32) NOT NULL CHECK (role IN ('project_admin', 'member')),
    created_at TIMESTAMPTZ(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    updated_at TIMESTAMPTZ(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    CONSTRAINT uk_project_members_project_user UNIQUE (project_id, user_id),
    CONSTRAINT fk_project_members_project FOREIGN KEY (project_id) REFERENCES projects (id) ON DELETE CASCADE,
    CONSTRAINT fk_project_members_user FOREIGN KEY (user_id) REFERENCES users (id) ON DELETE CASCADE
);

CREATE INDEX idx_project_members_user_id ON project_members (user_id);

CREATE TABLE audit_logs (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    actor_id BIGINT,
    project_id BIGINT,
    action VARCHAR(128) NOT NULL,
    resource_type VARCHAR(64) NOT NULL,
    resource_id VARCHAR(255),
    detail JSONB,
    request_ip VARCHAR(45),
    created_at TIMESTAMPTZ(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3)
);

CREATE INDEX idx_audit_logs_project_created_at ON audit_logs (project_id, created_at);
CREATE INDEX idx_audit_logs_actor_created_at ON audit_logs (actor_id, created_at);
CREATE INDEX idx_audit_logs_resource ON audit_logs (resource_type, resource_id);

CREATE TABLE resource_sources (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    project_id BIGINT NOT NULL,
    provider VARCHAR(32) NOT NULL CHECK (provider IN ('aliyun', 'aws')),
    name VARCHAR(128) NOT NULL,
    region VARCHAR(128) NOT NULL DEFAULT '',
    encrypted_credential TEXT NOT NULL,
    credential_hint VARCHAR(128) NOT NULL DEFAULT '',
    config JSONB,
    enabled BOOLEAN NOT NULL DEFAULT TRUE,
    sync_interval_minutes INTEGER NOT NULL DEFAULT 60 CHECK (sync_interval_minutes > 0),
    last_sync_at TIMESTAMPTZ(3),
    next_sync_at TIMESTAMPTZ(3),
    created_at TIMESTAMPTZ(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    updated_at TIMESTAMPTZ(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    CONSTRAINT fk_resource_sources_project FOREIGN KEY (project_id) REFERENCES projects (id) ON DELETE CASCADE
);

CREATE INDEX idx_resource_sources_project_provider ON resource_sources (project_id, provider);

CREATE TABLE resources_servers (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    project_id BIGINT NOT NULL,
    source_id BIGINT NOT NULL,
    provider VARCHAR(32) NOT NULL CHECK (provider IN ('aliyun', 'aws')),
    resource_type VARCHAR(64) NOT NULL,
    external_id VARCHAR(255) NOT NULL,
    name VARCHAR(255) NOT NULL DEFAULT '',
    region VARCHAR(128) NOT NULL DEFAULT '',
    zone VARCHAR(128) NOT NULL DEFAULT '',
    cloud_status VARCHAR(64) NOT NULL DEFAULT '',
    asset_status VARCHAR(32) NOT NULL DEFAULT 'active' CHECK (asset_status IN ('active', 'lost')),
    private_ips JSONB,
    public_ips JSONB,
    raw_attributes JSONB,
    first_seen_at TIMESTAMPTZ(3) NOT NULL,
    last_seen_at TIMESTAMPTZ(3) NOT NULL,
    missing_since TIMESTAMPTZ(3),
    created_at TIMESTAMPTZ(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    updated_at TIMESTAMPTZ(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    CONSTRAINT uk_resources_servers_identity UNIQUE (source_id, resource_type, external_id),
    CONSTRAINT fk_resources_servers_project FOREIGN KEY (project_id) REFERENCES projects (id) ON DELETE CASCADE,
    CONSTRAINT fk_resources_servers_source FOREIGN KEY (source_id) REFERENCES resource_sources (id) ON DELETE CASCADE
);

CREATE INDEX idx_resources_servers_project_provider ON resources_servers (project_id, provider);
CREATE INDEX idx_resources_servers_status ON resources_servers (asset_status);

CREATE TABLE resources_databases (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    project_id BIGINT NOT NULL,
    source_id BIGINT NOT NULL,
    provider VARCHAR(32) NOT NULL CHECK (provider IN ('aliyun', 'aws')),
    resource_type VARCHAR(64) NOT NULL,
    external_id VARCHAR(255) NOT NULL,
    name VARCHAR(255) NOT NULL DEFAULT '',
    region VARCHAR(128) NOT NULL DEFAULT '',
    zone VARCHAR(128) NOT NULL DEFAULT '',
    cloud_status VARCHAR(64) NOT NULL DEFAULT '',
    asset_status VARCHAR(32) NOT NULL DEFAULT 'active' CHECK (asset_status IN ('active', 'lost')),
    engine VARCHAR(64) NOT NULL DEFAULT '',
    engine_version VARCHAR(64) NOT NULL DEFAULT '',
    endpoints JSONB,
    raw_attributes JSONB,
    first_seen_at TIMESTAMPTZ(3) NOT NULL,
    last_seen_at TIMESTAMPTZ(3) NOT NULL,
    missing_since TIMESTAMPTZ(3),
    created_at TIMESTAMPTZ(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    updated_at TIMESTAMPTZ(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    CONSTRAINT uk_resources_databases_identity UNIQUE (source_id, resource_type, external_id),
    CONSTRAINT fk_resources_databases_project FOREIGN KEY (project_id) REFERENCES projects (id) ON DELETE CASCADE,
    CONSTRAINT fk_resources_databases_source FOREIGN KEY (source_id) REFERENCES resource_sources (id) ON DELETE CASCADE
);

CREATE INDEX idx_resources_databases_project_provider ON resources_databases (project_id, provider);
CREATE INDEX idx_resources_databases_status ON resources_databases (asset_status);

CREATE TABLE resources_load_balancers (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    project_id BIGINT NOT NULL,
    source_id BIGINT NOT NULL,
    provider VARCHAR(32) NOT NULL CHECK (provider IN ('aliyun', 'aws')),
    resource_type VARCHAR(64) NOT NULL,
    external_id VARCHAR(255) NOT NULL,
    name VARCHAR(255) NOT NULL DEFAULT '',
    region VARCHAR(128) NOT NULL DEFAULT '',
    zone VARCHAR(128) NOT NULL DEFAULT '',
    cloud_status VARCHAR(64) NOT NULL DEFAULT '',
    asset_status VARCHAR(32) NOT NULL DEFAULT 'active' CHECK (asset_status IN ('active', 'lost')),
    network_type VARCHAR(32) NOT NULL DEFAULT '',
    endpoints JSONB,
    raw_attributes JSONB,
    first_seen_at TIMESTAMPTZ(3) NOT NULL,
    last_seen_at TIMESTAMPTZ(3) NOT NULL,
    missing_since TIMESTAMPTZ(3),
    created_at TIMESTAMPTZ(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    updated_at TIMESTAMPTZ(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    CONSTRAINT uk_resources_load_balancers_identity UNIQUE (source_id, resource_type, external_id),
    CONSTRAINT fk_resources_load_balancers_project FOREIGN KEY (project_id) REFERENCES projects (id) ON DELETE CASCADE,
    CONSTRAINT fk_resources_load_balancers_source FOREIGN KEY (source_id) REFERENCES resource_sources (id) ON DELETE CASCADE
);

CREATE INDEX idx_resources_load_balancers_project_provider ON resources_load_balancers (project_id, provider);
CREATE INDEX idx_resources_load_balancers_status ON resources_load_balancers (asset_status);

CREATE TABLE sync_jobs (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    project_id BIGINT NOT NULL,
    source_id BIGINT NOT NULL,
    previous_job_id BIGINT,
    status VARCHAR(32) NOT NULL CHECK (status IN ('queued', 'running', 'success', 'partial_success', 'failed')),
    trigger VARCHAR(32) NOT NULL CHECK (trigger IN ('manual', 'scheduled')),
    statistics JSONB,
    error_summary VARCHAR(500) NOT NULL DEFAULT '',
    started_at TIMESTAMPTZ(3) NOT NULL,
    finished_at TIMESTAMPTZ(3),
    CONSTRAINT fk_sync_jobs_project FOREIGN KEY (project_id) REFERENCES projects (id) ON DELETE CASCADE,
    CONSTRAINT fk_sync_jobs_source FOREIGN KEY (source_id) REFERENCES resource_sources (id) ON DELETE CASCADE,
    CONSTRAINT fk_sync_jobs_previous FOREIGN KEY (previous_job_id) REFERENCES sync_jobs (id) ON DELETE SET NULL
);

CREATE INDEX idx_sync_jobs_source_started ON sync_jobs (source_id, started_at);
CREATE INDEX idx_sync_jobs_project_started ON sync_jobs (project_id, started_at);
CREATE INDEX idx_sync_jobs_previous ON sync_jobs (previous_job_id);
CREATE UNIQUE INDEX uk_sync_jobs_source_running ON sync_jobs (source_id) WHERE status = 'running';

COMMENT ON TABLE public.users IS 'CMDB 全局用户身份表';
COMMENT ON COLUMN public.users.id IS '全局用户唯一标识';
COMMENT ON COLUMN public.users.username IS '登录用户名，全局唯一';
COMMENT ON COLUMN public.users.password_hash IS 'bcrypt 密码哈希，禁止保存明文';
COMMENT ON COLUMN public.users.display_name IS '页面展示的用户名称';
COMMENT ON COLUMN public.users.email IS '用户联系邮箱';
COMMENT ON COLUMN public.users.global_role IS '全局角色，仅系统管理员或普通用户';
COMMENT ON COLUMN public.users.status IS '用户启用状态';
COMMENT ON COLUMN public.users.last_login_at IS '最近一次成功登录时间';
COMMENT ON COLUMN public.users.created_at IS '创建时间';
COMMENT ON COLUMN public.users.updated_at IS '最后更新时间，由应用更新时维护';

COMMENT ON TABLE public.projects IS 'CMDB 业务项目表，是系统最高级的数据归属和权限隔离边界';
COMMENT ON COLUMN public.projects.id IS '业务项目唯一标识';
COMMENT ON COLUMN public.projects.code IS '业务项目稳定编码，全局唯一且创建后不可修改';
COMMENT ON COLUMN public.projects.name IS '业务项目名称';
COMMENT ON COLUMN public.projects.description IS '业务项目说明';
COMMENT ON COLUMN public.projects.status IS '业务项目启用状态';
COMMENT ON COLUMN public.projects.owner_user_id IS '业务项目负责人，尚未分配时为空';
COMMENT ON COLUMN public.projects.created_at IS '创建时间';
COMMENT ON COLUMN public.projects.updated_at IS '最后更新时间，由应用更新时维护';

COMMENT ON TABLE public.project_members IS 'CMDB 业务项目成员与项目内角色表';
COMMENT ON COLUMN public.project_members.id IS '项目成员关系唯一标识';
COMMENT ON COLUMN public.project_members.project_id IS '所属业务项目标识';
COMMENT ON COLUMN public.project_members.user_id IS '成员用户标识';
COMMENT ON COLUMN public.project_members.role IS '用户在该业务项目内的角色';
COMMENT ON COLUMN public.project_members.created_at IS '加入项目时间';
COMMENT ON COLUMN public.project_members.updated_at IS '成员关系最后更新时间，由应用更新时维护';

COMMENT ON TABLE public.audit_logs IS 'CMDB 审计日志表，资源物理删除后仍保留';
COMMENT ON COLUMN public.audit_logs.id IS '审计日志唯一标识';
COMMENT ON COLUMN public.audit_logs.actor_id IS '执行操作的用户标识，用户删除后仍保留数值';
COMMENT ON COLUMN public.audit_logs.project_id IS '操作所属业务项目标识，项目删除后仍保留数值';
COMMENT ON COLUMN public.audit_logs.action IS '审计动作名称';
COMMENT ON COLUMN public.audit_logs.resource_type IS '被操作资源的类型';
COMMENT ON COLUMN public.audit_logs.resource_id IS '被操作资源的业务标识';
COMMENT ON COLUMN public.audit_logs.detail IS '已过滤敏感字段的审计上下文';
COMMENT ON COLUMN public.audit_logs.request_ip IS '请求来源 IP 地址';
COMMENT ON COLUMN public.audit_logs.created_at IS '审计记录创建时间';

COMMENT ON TABLE public.resource_sources IS 'CMDB 公有云平台接入源表';
COMMENT ON COLUMN public.resource_sources.id IS '云平台接入源唯一标识';
COMMENT ON COLUMN public.resource_sources.project_id IS '所属业务项目标识';
COMMENT ON COLUMN public.resource_sources.provider IS '云平台类型，仅阿里云或 AWS';
COMMENT ON COLUMN public.resource_sources.name IS '接入源名称';
COMMENT ON COLUMN public.resource_sources.region IS '云平台默认区域标识';
COMMENT ON COLUMN public.resource_sources.encrypted_credential IS '使用部署密钥加密后的云平台凭证';
COMMENT ON COLUMN public.resource_sources.credential_hint IS '凭证安全配置状态提示';
COMMENT ON COLUMN public.resource_sources.config IS '不含敏感信息的平台扩展配置';
COMMENT ON COLUMN public.resource_sources.enabled IS '是否启用自动同步';
COMMENT ON COLUMN public.resource_sources.sync_interval_minutes IS '自动同步间隔，单位为分钟';
COMMENT ON COLUMN public.resource_sources.last_sync_at IS '最近一次完成同步时间';
COMMENT ON COLUMN public.resource_sources.next_sync_at IS '下一次计划同步时间';
COMMENT ON COLUMN public.resource_sources.created_at IS '创建时间';
COMMENT ON COLUMN public.resource_sources.updated_at IS '最后更新时间，由应用更新时维护';

COMMENT ON TABLE public.resources_servers IS 'CMDB 云服务器资产表，保存 ECS 和 EC2 网卡内外网 IP';
COMMENT ON COLUMN public.resources_servers.id IS '服务器资产唯一标识';
COMMENT ON COLUMN public.resources_servers.project_id IS '所属业务项目标识';
COMMENT ON COLUMN public.resources_servers.source_id IS '来源接入源标识';
COMMENT ON COLUMN public.resources_servers.provider IS '云平台类型';
COMMENT ON COLUMN public.resources_servers.resource_type IS '云资源类型';
COMMENT ON COLUMN public.resources_servers.external_id IS '云平台侧资源唯一标识';
COMMENT ON COLUMN public.resources_servers.name IS '云资源名称';
COMMENT ON COLUMN public.resources_servers.region IS '云资源所属区域';
COMMENT ON COLUMN public.resources_servers.zone IS '云资源所属可用区';
COMMENT ON COLUMN public.resources_servers.cloud_status IS '云平台返回的资源状态';
COMMENT ON COLUMN public.resources_servers.asset_status IS 'CMDB 资产状态，正常或已失联';
COMMENT ON COLUMN public.resources_servers.private_ips IS '网卡内网 IP 地址数组';
COMMENT ON COLUMN public.resources_servers.public_ips IS '网卡公网 IP 地址数组';
COMMENT ON COLUMN public.resources_servers.raw_attributes IS '云平台返回的原始非凭证属性';
COMMENT ON COLUMN public.resources_servers.first_seen_at IS '首次发现时间';
COMMENT ON COLUMN public.resources_servers.last_seen_at IS '最近一次成功发现时间';
COMMENT ON COLUMN public.resources_servers.missing_since IS '首次判定失联时间';
COMMENT ON COLUMN public.resources_servers.created_at IS '创建时间';
COMMENT ON COLUMN public.resources_servers.updated_at IS '最后更新时间，由应用更新时维护';

COMMENT ON TABLE public.resources_databases IS 'CMDB 云数据库资产表，保存 RDS 原始域名、端口和最近解析 IP';
COMMENT ON COLUMN public.resources_databases.id IS '数据库资产唯一标识';
COMMENT ON COLUMN public.resources_databases.project_id IS '所属业务项目标识';
COMMENT ON COLUMN public.resources_databases.source_id IS '来源接入源标识';
COMMENT ON COLUMN public.resources_databases.provider IS '云平台类型';
COMMENT ON COLUMN public.resources_databases.resource_type IS '云资源类型';
COMMENT ON COLUMN public.resources_databases.external_id IS '云平台侧资源唯一标识';
COMMENT ON COLUMN public.resources_databases.name IS '云资源名称';
COMMENT ON COLUMN public.resources_databases.region IS '云资源所属区域';
COMMENT ON COLUMN public.resources_databases.zone IS '云资源所属可用区';
COMMENT ON COLUMN public.resources_databases.cloud_status IS '云平台返回的资源状态';
COMMENT ON COLUMN public.resources_databases.asset_status IS 'CMDB 资产状态，正常或已失联';
COMMENT ON COLUMN public.resources_databases.engine IS '数据库引擎';
COMMENT ON COLUMN public.resources_databases.engine_version IS '数据库引擎版本';
COMMENT ON COLUMN public.resources_databases.endpoints IS '原始访问域名、端口和最近解析 IP';
COMMENT ON COLUMN public.resources_databases.raw_attributes IS '云平台返回的原始非凭证属性';
COMMENT ON COLUMN public.resources_databases.first_seen_at IS '首次发现时间';
COMMENT ON COLUMN public.resources_databases.last_seen_at IS '最近一次成功发现时间';
COMMENT ON COLUMN public.resources_databases.missing_since IS '首次判定失联时间';
COMMENT ON COLUMN public.resources_databases.created_at IS '创建时间';
COMMENT ON COLUMN public.resources_databases.updated_at IS '最后更新时间，由应用更新时维护';

COMMENT ON TABLE public.resources_load_balancers IS 'CMDB 云负载均衡资产表，保存原始域名、端口和最近解析 IP';
COMMENT ON COLUMN public.resources_load_balancers.id IS '负载均衡资产唯一标识';
COMMENT ON COLUMN public.resources_load_balancers.project_id IS '所属业务项目标识';
COMMENT ON COLUMN public.resources_load_balancers.source_id IS '来源接入源标识';
COMMENT ON COLUMN public.resources_load_balancers.provider IS '云平台类型';
COMMENT ON COLUMN public.resources_load_balancers.resource_type IS '云资源类型';
COMMENT ON COLUMN public.resources_load_balancers.external_id IS '云平台侧资源唯一标识';
COMMENT ON COLUMN public.resources_load_balancers.name IS '云资源名称';
COMMENT ON COLUMN public.resources_load_balancers.region IS '云资源所属区域';
COMMENT ON COLUMN public.resources_load_balancers.zone IS '云资源所属可用区';
COMMENT ON COLUMN public.resources_load_balancers.cloud_status IS '云平台返回的资源状态';
COMMENT ON COLUMN public.resources_load_balancers.asset_status IS 'CMDB 资产状态，正常或已失联';
COMMENT ON COLUMN public.resources_load_balancers.network_type IS '负载均衡网络类型';
COMMENT ON COLUMN public.resources_load_balancers.endpoints IS '原始访问域名、端口和最近解析 IP';
COMMENT ON COLUMN public.resources_load_balancers.raw_attributes IS '云平台返回的原始非凭证属性';
COMMENT ON COLUMN public.resources_load_balancers.first_seen_at IS '首次发现时间';
COMMENT ON COLUMN public.resources_load_balancers.last_seen_at IS '最近一次成功发现时间';
COMMENT ON COLUMN public.resources_load_balancers.missing_since IS '首次判定失联时间';
COMMENT ON COLUMN public.resources_load_balancers.created_at IS '创建时间';
COMMENT ON COLUMN public.resources_load_balancers.updated_at IS '最后更新时间，由应用更新时维护';

COMMENT ON TABLE public.sync_jobs IS 'CMDB 云资源同步任务与重试历史表';
COMMENT ON COLUMN public.sync_jobs.id IS '同步任务唯一标识';
COMMENT ON COLUMN public.sync_jobs.project_id IS '所属业务项目标识';
COMMENT ON COLUMN public.sync_jobs.source_id IS '执行同步的接入源标识';
COMMENT ON COLUMN public.sync_jobs.previous_job_id IS '失败重试所关联的原任务标识';
COMMENT ON COLUMN public.sync_jobs.status IS '任务状态，排队、运行、成功、部分成功或失败';
COMMENT ON COLUMN public.sync_jobs.trigger IS '触发方式，手工或定时';
COMMENT ON COLUMN public.sync_jobs.statistics IS '各资源类型的脱敏同步统计';
COMMENT ON COLUMN public.sync_jobs.error_summary IS '不含敏感信息的失败摘要';
COMMENT ON COLUMN public.sync_jobs.started_at IS '任务开始时间';
COMMENT ON COLUMN public.sync_jobs.finished_at IS '任务完成时间';

-- 禁止 PUBLIC 与应用账号创建业务对象；管理员创建的表和序列由 cmdb 按最小权限读写。
REVOKE CREATE ON SCHEMA public FROM PUBLIC;
REVOKE ALL ON SCHEMA public FROM cmdb;
REVOKE ALL ON ALL TABLES IN SCHEMA public FROM PUBLIC;
REVOKE ALL ON ALL SEQUENCES IN SCHEMA public FROM PUBLIC;
GRANT USAGE ON SCHEMA public TO cmdb;
GRANT SELECT, INSERT, UPDATE, DELETE ON ALL TABLES IN SCHEMA public TO cmdb;
GRANT USAGE, SELECT ON ALL SEQUENCES IN SCHEMA public TO cmdb;
ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT SELECT, INSERT, UPDATE, DELETE ON TABLES TO cmdb;
ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT USAGE, SELECT ON SEQUENCES TO cmdb;

COMMIT;
