-- CMDB 云资源初始化结构：接入源、三类资产和同步任务。
SET NAMES utf8mb4 COLLATE utf8mb4_0900_ai_ci;
CREATE TABLE IF NOT EXISTS resource_sources (
 id BIGINT UNSIGNED AUTO_INCREMENT COMMENT '接入源主键', project_id BIGINT UNSIGNED NOT NULL COMMENT '所属项目', provider ENUM('aliyun','aws') NOT NULL COMMENT '云平台', name VARCHAR(128) NOT NULL COMMENT '名称', region VARCHAR(128) NOT NULL DEFAULT '' COMMENT '默认区域', encrypted_credential TEXT NOT NULL COMMENT '加密凭证', credential_hint VARCHAR(128) NOT NULL DEFAULT '' COMMENT '凭证提示', config JSON COMMENT '非敏感配置', enabled BOOLEAN NOT NULL DEFAULT TRUE COMMENT '是否启用', sync_interval_minutes INT NOT NULL DEFAULT 60 COMMENT '同步周期分钟', last_sync_at DATETIME(3) COMMENT '最近同步时间', next_sync_at DATETIME(3) COMMENT '下次同步时间', created_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) COMMENT '创建时间', updated_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3) COMMENT '更新时间', PRIMARY KEY(id), KEY idx_sources_project_provider(project_id,provider), CONSTRAINT fk_sources_project FOREIGN KEY(project_id) REFERENCES projects(id) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci COMMENT='公有云平台接入源';

CREATE TABLE IF NOT EXISTS resources_servers (
 id BIGINT UNSIGNED AUTO_INCREMENT COMMENT '服务器资产主键', project_id BIGINT UNSIGNED NOT NULL COMMENT '所属项目', source_id BIGINT UNSIGNED NOT NULL COMMENT '接入源', provider VARCHAR(32) NOT NULL COMMENT '云平台', resource_type VARCHAR(64) NOT NULL COMMENT '资源类型', external_id VARCHAR(255) NOT NULL COMMENT '云端唯一 ID', name VARCHAR(255) NOT NULL DEFAULT '' COMMENT '名称', region VARCHAR(128) NOT NULL DEFAULT '' COMMENT '区域', zone VARCHAR(128) NOT NULL DEFAULT '' COMMENT '可用区', cloud_status VARCHAR(64) NOT NULL DEFAULT '' COMMENT '云端状态', asset_status ENUM('active','lost') NOT NULL DEFAULT 'active' COMMENT '资产状态', private_ips JSON COMMENT '私网 IP 数组', public_ips JSON COMMENT '公网 IP 数组', raw_attributes JSON COMMENT '云端原始属性', first_seen_at DATETIME(3) NOT NULL COMMENT '首次发现时间', last_seen_at DATETIME(3) NOT NULL COMMENT '最近完整同步发现时间', missing_since DATETIME(3) COMMENT '失联起始时间', created_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) COMMENT '创建时间', updated_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3) COMMENT '更新时间', PRIMARY KEY(id), UNIQUE KEY uk_resources_servers_identity(source_id,resource_type,external_id), KEY idx_resources_servers_project(project_id,provider), KEY idx_resources_servers_status(asset_status), CONSTRAINT fk_resources_servers_project FOREIGN KEY(project_id) REFERENCES projects(id) ON DELETE CASCADE, CONSTRAINT fk_resources_servers_source FOREIGN KEY(source_id) REFERENCES resource_sources(id) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci COMMENT='云服务器资产';

CREATE TABLE IF NOT EXISTS resources_databases (
 id BIGINT UNSIGNED AUTO_INCREMENT COMMENT '数据库资产主键', project_id BIGINT UNSIGNED NOT NULL COMMENT '所属项目', source_id BIGINT UNSIGNED NOT NULL COMMENT '接入源', provider VARCHAR(32) NOT NULL COMMENT '云平台', resource_type VARCHAR(64) NOT NULL COMMENT '资源类型', external_id VARCHAR(255) NOT NULL COMMENT '云端唯一 ID', name VARCHAR(255) NOT NULL DEFAULT '' COMMENT '名称', region VARCHAR(128) NOT NULL DEFAULT '' COMMENT '区域', zone VARCHAR(128) NOT NULL DEFAULT '' COMMENT '可用区', cloud_status VARCHAR(64) NOT NULL DEFAULT '' COMMENT '云端状态', asset_status ENUM('active','lost') NOT NULL DEFAULT 'active' COMMENT '资产状态', engine VARCHAR(64) NOT NULL DEFAULT '' COMMENT '数据库引擎', engine_version VARCHAR(64) NOT NULL DEFAULT '' COMMENT '引擎版本', endpoints JSON COMMENT '访问端点、端口及解析 IP', raw_attributes JSON COMMENT '云端原始属性', first_seen_at DATETIME(3) NOT NULL COMMENT '首次发现时间', last_seen_at DATETIME(3) NOT NULL COMMENT '最近完整同步发现时间', missing_since DATETIME(3) COMMENT '失联起始时间', created_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) COMMENT '创建时间', updated_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3) COMMENT '更新时间', PRIMARY KEY(id), UNIQUE KEY uk_resources_databases_identity(source_id,resource_type,external_id), KEY idx_resources_databases_project(project_id,provider), KEY idx_resources_databases_status(asset_status), CONSTRAINT fk_resources_databases_project FOREIGN KEY(project_id) REFERENCES projects(id) ON DELETE CASCADE, CONSTRAINT fk_resources_databases_source FOREIGN KEY(source_id) REFERENCES resource_sources(id) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci COMMENT='云数据库资产';

CREATE TABLE IF NOT EXISTS resources_load_balancers (
 id BIGINT UNSIGNED AUTO_INCREMENT COMMENT '负载均衡资产主键', project_id BIGINT UNSIGNED NOT NULL COMMENT '所属项目', source_id BIGINT UNSIGNED NOT NULL COMMENT '接入源', provider VARCHAR(32) NOT NULL COMMENT '云平台', resource_type VARCHAR(64) NOT NULL COMMENT '资源类型', external_id VARCHAR(255) NOT NULL COMMENT '云端唯一 ID', name VARCHAR(255) NOT NULL DEFAULT '' COMMENT '名称', region VARCHAR(128) NOT NULL DEFAULT '' COMMENT '区域', zone VARCHAR(128) NOT NULL DEFAULT '' COMMENT '可用区', cloud_status VARCHAR(64) NOT NULL DEFAULT '' COMMENT '云端状态', asset_status ENUM('active','lost') NOT NULL DEFAULT 'active' COMMENT '资产状态', network_type VARCHAR(32) NOT NULL DEFAULT '' COMMENT '网络类型', endpoints JSON COMMENT '访问端点、端口及解析 IP', raw_attributes JSON COMMENT '云端原始属性', first_seen_at DATETIME(3) NOT NULL COMMENT '首次发现时间', last_seen_at DATETIME(3) NOT NULL COMMENT '最近完整同步发现时间', missing_since DATETIME(3) COMMENT '失联起始时间', created_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) COMMENT '创建时间', updated_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3) COMMENT '更新时间', PRIMARY KEY(id), UNIQUE KEY uk_resources_load_balancers_identity(source_id,resource_type,external_id), KEY idx_resources_load_balancers_project(project_id,provider), KEY idx_resources_load_balancers_status(asset_status), CONSTRAINT fk_resources_load_balancers_project FOREIGN KEY(project_id) REFERENCES projects(id) ON DELETE CASCADE, CONSTRAINT fk_resources_load_balancers_source FOREIGN KEY(source_id) REFERENCES resource_sources(id) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci COMMENT='云负载均衡资产';

CREATE TABLE IF NOT EXISTS sync_jobs (
 id BIGINT UNSIGNED AUTO_INCREMENT COMMENT '同步任务主键', project_id BIGINT UNSIGNED NOT NULL COMMENT '所属项目', source_id BIGINT UNSIGNED NOT NULL COMMENT '接入源', status ENUM('queued','running','success','partial_success','failed') NOT NULL COMMENT '任务状态', `trigger` ENUM('manual','scheduled') NOT NULL COMMENT '触发方式', statistics JSON COMMENT '分类统计', error_summary VARCHAR(500) NOT NULL DEFAULT '' COMMENT '脱敏错误摘要', started_at DATETIME(3) NOT NULL COMMENT '开始时间', finished_at DATETIME(3) COMMENT '结束时间', PRIMARY KEY(id), KEY idx_jobs_source_started(source_id,started_at), KEY idx_jobs_project_started(project_id,started_at), CONSTRAINT fk_jobs_project FOREIGN KEY(project_id) REFERENCES projects(id) ON DELETE CASCADE, CONSTRAINT fk_jobs_source FOREIGN KEY(source_id) REFERENCES resource_sources(id) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci COMMENT='云资源同步任务';
